spring:

  output:
    ansi:
      enabled: always

  liquibase:
    enabled: on
    change-log: db/master.yml

  docker:
    compose:
      file: src/main/docker/gypsogest.yml
      enabled: on
      lifecycle-management: start_and_stop

  datasource:
    url: jdbc:mysql://localhost:3306/gypsogest
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
